{% extends 'admin/base.phtml' %}

{% block container %}

	<div class="panel panel-success">
	    <div class="panel-heading">
	      <h3 class="panel-title">Add mission</h3>
	    </div>
	    <div class="panel-body">
		  <form method="post">
		    {{form.title.label}}: {{form.title}} <br/>
		    {{form.description.label}}:<br/>
		    {{form.description }} <br/>
		    {{form.submit(class="btn btn-default")}}
		  </form>
	    
	      {% if error %}
	      <div class="alert alert-danger" >
	        {{error}}
	      </div>
          {% endif %}
	    </div>
     </div>

{% endblock %}
