{% extends 'admin/base.phtml' %}

{% block container %}

	<div class="panel panel-success">
	    <div class="panel-heading">
	      <h3 class="panel-title">Add problem</h3>
	    </div>
	    <div class="panel-body">
	      <div class="alert alert-info" >Mission: {{mission.title|e}}</div>
		  <form method="post" action='/addproblem'>
		    <div style="display:none;" >{{form.mission_id}}</div>
		    {{form.title.label}}: {{form.title}} <br/>
		    {{form.description.label}}:<br/>
		    {{form.description }} <br/>
		    {{form.submit(class="btn btn-default")}}
		  </form>
	    
          {% if error %}
	      <div class="alert alert-danger" >
	        {{error}}
	      </div>
	      {% endif %}
	    </div>
     </div>

{% endblock %}
