#!/usr/bin/python
import os
import sys
from os.path import dirname

sys.path.insert(0, dirname(dirname(__file__)))

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

# addidional environ parameters
os.environ.update({'CDN': '/static',
                   'TEMPLATES_AUTORELOAD': '0',
                   'DBNAME': os.environ['OPENSHIFT_APP_NAME']})

from ideasphere.app import Application

application = Application()
