<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}{% endblock %}</title>
  {% block styles  %}
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  {% endblock %}

  {% block scripts %}
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="{{cdn}}/css/jquery-ui-1.9.cupertino.min.css" />
    <style>
      .ui-widget {font-size: 80%}
    </style>
  {% endblock %}

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="description" content="{% block meta_desc %}{% endblock %}" />
  <meta name="keywords" content="{% block meta_keywords %}{% endblock %}" />

  {% block head_rest %}{% endblock %}
</head>

<body>
  {% block body %}{% endblock %}
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>
