{% extends 'base.phtml' %}

{% block styles %}
  {{ super() }}
  <style>
   textarea { margin: 0px; width: 313px; height: 86px; }
  </style>
{% endblock %}



{% block body %}

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% block top_navbar %}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">IDEASPHERE</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            {#
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            #}
          </ul>

          <div class="navbar-form navbar-right " style="color:#FFFFFF; font-size:14px;"  >
            {% if user %}
                {% if user.img_url %}
                  <img src="{{user.img_url}}" width="32"/>
                {% endif %}
                <span>{{user.alias }}</span>
              <a href="/logout" ><button class="btn btn-default">Logout</button></a>
            {% else %}
              <span>Login with</span>
              <a href="/login/g/{{url_quote(path)[1:]}}" ><img  width="32" src="{{cdn}}/img/g-icon.png" /></a>
            {% endif %}

          </div>
        </div>
      </div>
    {% endblock %}
    </div>

  <div class="container">
  {% block container %}{% endblock %}
  </div>

{% endblock %}
