{% extends 'base.phtml' %}

{% block styles %}
  {{ super() }}
  <style>
   textarea { margin: 0px; width: 313px; height: 86px; }
  </style>
{% endblock %}

{% block body %}

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% block top_navbar %}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">IDEASPHERE</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            {% if user.is_admin %}
              <li><a href="/addmission">Add mission</a></li>
            {% endif %}
          </ul>

          <div class="navbar-form navbar-right " style="color:#FFFFFF; font-size:14px;"  >
            {% if user %}
                {% if user.img_url %}
                  <a href="/user/{{user.id}}" ><img src="{{user.img_url}}" width="32"/></a>
                {% endif %}
                <span>{{user.alias }}</span>
              <a href="/logout" ><button class="btn btn-default">Logout</button></a>
            {% else %}
              <span>Login with</span>
              <a href="/login/g/{{url_quote(path)[1:]}}"  ><img  width="32" src="{{cdn}}/img/g-icon.png" /></a>
              <a href="/login/fb/{{url_quote(path)[1:]}}" ><img  width="34" src="{{cdn}}/img/fb-icon.png" /></a>
            {% endif %}

          </div>
        </div>
      </div>
    {% endblock %}
    </div>

  <div class="container">
  {% block container %}{% endblock %}
  </div>

{% endblock %}
