{% extends 'default.phtml' %}

{% block scripts %}
  {{super()}}
  <script>
    var proposal_id={{proposal.id}};
  </script>
  
{% endblock %}

{% block container %}
	<div class="panel panel-success">
	    <div class="panel-heading">
	      <h2 class="panel-title">mission:
	         <a href="/mission/{{problem.mission_id}}" >{{problem.mission.title|e}}</a></h2>
	    </div>
	    <div class="panel-body">
	      problem:
	      <h3>{{problem.title|e}}</h3>
	      <div>{{problem.description|e}}</div>
	      <hr/>
	      <div>
	        <b>{{proposal.score() }} votes</b>
  	        proposal by: <a href="/profile/{{proposal.user_id}}" >{{proposal.submiter.alias|e}}</a>
	        posted on {{proposal.submited.strftime('%B %d, %Y') }}
	      </div>
	      <div>
	        <b>{{proposal.title|e}}</b> <br/>
	        {{proposal.description|e}}
	      </div>
	      <img  src="data:image/png;base64,{{img64}}"
	          class="ui-resizable" style="width: 400px;" />
	          
	      {% if user %}
	      {# voting part #}
	        {% if user.id != proposal.user_id %}
	        <div id="voting" >
  	          <button class="btn btn-sm {% if vote is not none and vote.is_plus %}btn-warning{%else%}btn-primary{% endif %} " 
  	              id="vote_up" >vote up!</button>
  	          <button class="btn btn-sm {% if vote is not none and not vote.is_plus %}btn-warning{%else%}btn-primary{% endif %} "
  	              id="vote_down" >vote down</button>
  	        </div>
  	        
  	        <script>
  	        function vote(val) {
  	          $.get('/vote/'+proposal_id+'/'+val, {}, function(){});
  	        }
  	        
  	        $('#vote_up').click(function(){
  	            vote(1);
  	            $("button[id^=vote_down]").removeClass("btn-warning").addClass("btn-primary");
  	            $("button[id^=vote_up]").removeClass("btn-primary").addClass("btn-warning");
  	        });
  	        $('#vote_down').click(function(){
  	            vote(0);
  	            $("button[id^=vote_up]").removeClass("btn-warning").addClass("btn-primary");
  	            $("button[id^=vote_down]").removeClass("btn-primary").addClass("btn-warning");
  	        });
  	        </script>
	        {% endif %}
	      
	      {% endif %}
	    </div>
    </div>

{% endblock  %}
